apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: appdev-kafka
  name: kafka-connect-camel-jdbc
  annotations:
    strimzi.io/use-connector-resources: "true"  
spec:
  config:
    group.id: connect-cluster2
    offset.storage.topic: connect-cluster-offsets2
    config.storage.topic: connect-cluster-configs2
    status.storage.topic: connect-cluster-status2
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1    
  bootstrapServers: 'event-broker-dr-kafka-bootstrap.appdev-kafka.svc:9092'
  build:
    output:
      image: >-
        image-registry.openshift-image-registry.svc:5000/appdev-kafka/camel-sql-kafka-connect:0.11.5
      type: docker
    plugins:
      - name: camel-sql-kafka-connector
        artifacts:
          - url: https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-sql-kafka-connector/0.11.5/camel-sql-kafka-connector-0.11.5-package.tar.gz
            type: tgz
      - name: mssql-jdbc
        artifacts:
          - url: https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/10.2.1.jre11/mssql-jdbc-10.2.1.jre11.jar
            type: jar
  version: 3.1.0
  replicas: 1
